language: python
cache:
    directories:
        - /home/travis/virtualenv/python2.7.9/
python:
    - "2.7"
install: 
 - pip install --upgrade pip setuptools
 - pip install -e .[develop]
script:
    - py.test
    - flake8
    - sphinx-build -W -b html -qa -E docs docs/_build/html
