---

version: 1
disable_existing_loggers: false
formatters:
  precise:
    format: '%(asctime)s - %(username)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: precise
    maxBytes: 10485760
    backupCount: 3

root:
  level: DEBUG
  handlers: [console, file]

...
